baseURL = 'http://lilinfangrelax.github.io'
languageCode = 'zh-cn'
title = "dotnet notes"

[module]

proxy = "direct"

[[module.imports]]

path = "github.com/google/docsy"


[[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/lilinfangrelax"

#设置默认值
#[[cascade]]
#type = "docs"
#  [cascade._target]
#  path = "/**"


[params]
#设置离线搜索
#offlineSearch = true
#offlineSearchSummaryLength = 200
#offlineSearchMaxResults = 25
# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "a112ed1dff70a4869"


[params.ui]
#关闭侧边栏
#sidebar_search_disable = true
#开启白天黑夜模式
showLightDarkModeMenu = true

[markup]
  [markup.highlight]